[project]
name = "experiment-nutpie-gpu"
version = "0.1.0"
description = "Add a short description here"
authors = ["Adrian Seyboldt <adrian.seyboldt@gmail.com>"]
channels = ["pytorch", "conda-forge"]
platforms = ["linux-64"]

[tasks]
install-nutpie = "cd nutpie; maturin develop --release"

[dependencies]
python = ">=3.11.9,<3.12"
pytorch = { version = ">=2.3.0,<2.4", build = "*cpu*" }
jaxlib = { version = ">=0.4.23,<0.5", build = "*cuda12*" }
numpyro = ">=0.14.0,<0.15"
pymc = ">=5.14.0,<5.15"
ipykernel = ">=6.29.3,<6.30"
blackjax = ">=1.1.1,<1.2"
maturin = ">=1.5.1,<1.6"
pip = ">=24.0,<25"
pyarrow = ">=15.0.2,<15.1"

[pypi-dependencies]
onnxscript = "*"

[system-requirements]
cuda = "12"
